site_name: GentzkowLabTemplate Docs
# site_description: TBD
site_url: https://gentzkowlab.github.io/GentzkowLabTemplate/
repo_url: https://github.com/gentzkowlab/GentzkowLabTemplate
edit_uri: edit/docs/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.prune
    - toc.follow
    # - toc.integrate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.last-updated
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/eye
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    logo: octicons/repo-template-24
  favicon: assets/images/lab-icon-dark.png

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

copyright: "&copy; 2025 GentzkowLab"

plugins:
  - search

extra:
  generator: false
  link_external_new_tab: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 
    - Welcome: index.md
    - How to use this guide: home/how_to.md
